---

services:
    transformers-notebook:
        build: ./
        ports:
            - 8000:8888
        environment:
            - JUPYTER_TOKEN=helpmelord
        volumes:
            -  ./:/home/jovyan
...